"""
HTML-based PDF resume generator using Jinja2 templates and WeasyPrint.
"""
from pathlib import Path
from typing import Optional
from jinja2 import Environment, FileSystemLoader, select_autoescape
from weasyprint import HTML
from resume_parser import ResumeData


class HTMLResumePDFGenerator:
    """Generate professionally formatted PDF resumes from HTML templates."""
    
    AVAILABLE_TEMPLATES = ['modern', 'professional', 'minimal']

    # Applied after each template's own styles so resumes generated by the app
    # share compact one-page and flowing multi-page print layouts.
    COMPACT_PRINT_STYLES = """
        @page { size: letter; margin: 0.38in 0.45in; }
        body { font-size: 9pt !important; line-height: 1.16 !important; }
        .container { max-width: none; }
        .header {
            margin: 0 0 7px !important;
            padding: 6px 5px !important;
        }
        .name {
            font-size: 20pt !important;
            letter-spacing: 0.5px !important;
            margin-bottom: 3px !important;
        }
        .contact-info { font-size: 8.5pt !important; line-height: 1.15 !important; }
        .separator { margin-left: 4px !important; margin-right: 4px !important; }
        .section { margin-bottom: 6px !important; page-break-inside: auto !important; }
        .section-title {
            font-size: 10.5pt !important;
            letter-spacing: 0.5px !important;
            margin-bottom: 3px !important;
            padding: 2px 5px !important;
            border-bottom-width: 1px !important;
        }
        .summary-text {
            font-size: 9pt !important;
            line-height: 1.16 !important;
            margin-bottom: 2px !important;
            padding: 3px 5px !important;
        }
        .entry {
            margin-bottom: 5px !important;
            padding: 3px 5px !important;
            page-break-inside: avoid;
        }
        .entry-header, .project-header { margin-bottom: 1px !important; }
        .entry-title, .project-title { font-size: 9.5pt !important; }
        .entry-date, .project-date, .gpa { font-size: 8pt !important; }
        .entry-subtitle { font-size: 8.5pt !important; margin-bottom: 2px !important; }
        .bullets, .honors { margin-top: 2px !important; margin-left: 14px !important; }
        .bullet, .honor, .cert {
            font-size: 9pt !important;
            line-height: 1.14 !important;
            margin-bottom: 1px !important;
        }
        .bullet::before, .honor::before, .cert::before { font-size: 9pt !important; }
        .skills-text { font-size: 9pt !important; line-height: 1.16 !important; }
        .gpa { margin-top: 1px !important; }
        .cert { margin-left: 14px !important; }
    """

    PAGINATED_PRINT_STYLES = """
        @page { size: letter; margin: 0.5in 0.55in; }
        body { font-size: 10pt !important; line-height: 1.28 !important; }
        .header { margin: 0 0 9px !important; padding: 6px 5px !important; }
        .name { font-size: 24pt !important; letter-spacing: 1px !important; margin-bottom: 5px !important; }
        .contact-info { font-size: 9pt !important; line-height: 1.25 !important; }
        .section {
            margin-bottom: 9px !important;
            page-break-inside: auto !important;
            break-inside: auto !important;
        }
        .section-title { font-size: 12pt !important; margin-bottom: 6px !important; }
        .summary-text { font-size: 10pt !important; line-height: 1.25 !important; }
        .entry { margin-bottom: 8px !important; page-break-inside: avoid; break-inside: avoid; }
        .entry-title, .project-title { font-size: 11pt !important; }
        .entry-date, .project-date, .gpa { font-size: 9pt !important; }
        .entry-subtitle { font-size: 9.5pt !important; margin-bottom: 4px !important; }
        .bullets, .honors { margin-top: 3px !important; margin-left: 17px !important; }
        .bullet, .honor, .cert { font-size: 9.5pt !important; line-height: 1.25 !important; margin-bottom: 2px !important; }
        .bullet::before, .honor::before, .cert::before { font-size: 9.5pt !important; }
        .skills-text { font-size: 10pt !important; line-height: 1.3 !important; }
        .cert { margin-left: 17px !important; }
    """
    
    def __init__(self, template_name: str = 'modern'):
        """
        Initialize PDF generator with HTML template.
        
        Args:
            template_name: Name of the template to use (modern, professional, minimal)
        """
        if template_name not in self.AVAILABLE_TEMPLATES:
            raise ValueError(
                f"Template '{template_name}' not found. "
                f"Available templates: {', '.join(self.AVAILABLE_TEMPLATES)}"
            )
        
        self.template_name = template_name
        
        # Set up Jinja2 environment
        template_dir = Path(__file__).parent / 'templates'
        self.env = Environment(
            loader=FileSystemLoader(str(template_dir)),
            autoescape=select_autoescape(['html', 'xml'])
        )
        
        # Load template
        self.template = self.env.get_template(f'{template_name}.html')
    
    def generate_pdf(
        self, 
        resume: ResumeData, 
        job_title: Optional[str] = None, 
        company: Optional[str] = None
    ) -> bytes:
        """
        Generate PDF resume from ResumeData using HTML template.
        
        Args:
            resume: ResumeData Pydantic model with structured resume data
            job_title: Optional job title (not used in rendering but kept for compatibility)
            company: Optional company name (not used in rendering but kept for compatibility)
            
        Returns:
            PDF file as bytes
        """
        # Prepare data for template
        template_data = {
            'contact': {
                'name': resume.contact.name,
                'email': resume.contact.email,
                'phone': resume.contact.phone,
                'location': resume.contact.location,
                'linkedin': resume.contact.linkedin,
                'github': resume.contact.github,
            },
            'summary': resume.summary,
            'experience': [
                {
                    'title': exp.title,
                    'company': exp.company,
                    'location': exp.location,
                    'start_date': exp.start_date,
                    'end_date': exp.end_date,
                    'bullets': exp.bullets,
                }
                for exp in resume.experience
            ],
            'education': [
                {
                    'degree': edu.degree,
                    'institution': edu.institution,
                    'location': edu.location,
                    'start_date': edu.start_date,
                    'end_date': edu.end_date,
                    'gpa': edu.gpa,
                    'honors': edu.honors,
                }
                for edu in resume.education
            ],
            'skills': resume.skills,
            'projects': [
                {
                    'title': proj.title,
                    'date': proj.date,
                    'description': proj.description,
                    'technologies': proj.technologies,
                    'bullets': proj.bullets,
                }
                for proj in resume.projects
            ],
            'certifications': [
                {
                    'name': cert.name,
                    'issuer': cert.issuer,
                    'date': cert.date,
                }
                for cert in resume.certifications
            ],
        }
        
        # Render HTML
        html_content = self._render_html(template_data)
        
        # Convert HTML to PDF using WeasyPrint
        pdf_bytes = HTML(string=html_content).write_pdf()
        
        return pdf_bytes
    
    def generate_html(self, resume: ResumeData) -> str:
        """
        Generate HTML resume (for preview/debugging).
        
        Args:
            resume: ResumeData Pydantic model with structured resume data
            
        Returns:
            HTML string
        """
        template_data = {
            'contact': {
                'name': resume.contact.name,
                'email': resume.contact.email,
                'phone': resume.contact.phone,
                'location': resume.contact.location,
                'linkedin': resume.contact.linkedin,
                'github': resume.contact.github,
            },
            'summary': resume.summary,
            'experience': [
                {
                    'title': exp.title,
                    'company': exp.company,
                    'location': exp.location,
                    'start_date': exp.start_date,
                    'end_date': exp.end_date,
                    'bullets': exp.bullets,
                }
                for exp in resume.experience
            ],
            'education': [
                {
                    'degree': edu.degree,
                    'institution': edu.institution,
                    'location': edu.location,
                    'start_date': edu.start_date,
                    'end_date': edu.end_date,
                    'gpa': edu.gpa,
                    'honors': edu.honors,
                }
                for edu in resume.education
            ],
            'skills': resume.skills,
            'projects': [
                {
                    'title': proj.title,
                    'date': proj.date,
                    'description': proj.description,
                    'technologies': proj.technologies,
                    'bullets': proj.bullets,
                }
                for proj in resume.projects
            ],
            'certifications': [
                {
                    'name': cert.name,
                    'issuer': cert.issuer,
                    'date': cert.date,
                }
                for cert in resume.certifications
            ],
        }
        
        return self._render_html(template_data)

    def _render_html(self, template_data: dict) -> str:
        """Prefer a compact layout while preserving natural page flow."""
        html_content = self.template.render(**template_data)
        compact_styles = f"<style>{self.COMPACT_PRINT_STYLES}</style>"
        compact_html = html_content.replace("</head>", f"{compact_styles}</head>", 1)

        # Measure the rendered result before choosing it so content is never
        # clipped to force a single-page output.
        compact_document = HTML(string=compact_html).render()
        if len(compact_document.pages) <= 2:
            return compact_html

        # If the compact version still overflows two pages, use a roomier
        # two-page style. Sections may continue across pages so a long
        # experience section cannot leave most of page one empty.
        paginated_styles = f"<style>{self.PAGINATED_PRINT_STYLES}</style>"
        return html_content.replace("</head>", f"{paginated_styles}</head>", 1)
    
    @classmethod
    def list_templates(cls) -> list[str]:
        """Return list of available template names."""
        return cls.AVAILABLE_TEMPLATES.copy()
